### ISSUE TITLE
Access violation with hw1 having two accounts

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1213]
My last successful transaction with the HW1 was four days ago. Today it didn't work any more. The strange thing is, that it also doesn't work, if I check out the revision from 4 days ago, or any random revision from the last two weeks. 
I can open the hw1 wallet if the dongle is not connected. But as soon as I plug it in, electrum starts to behave strangely, and eventually crashes. When I open electrum with the dongle plugged in, and the -w option to select the hw1 wallet, it mostly crashes during startup: 

r@q:~/sourcecode/electrum$ ./electrum -w ~/.electrum/wallets/hw1 QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
python2: Fatal IO error 11 (Die Ressource ist zur Zeit nicht verfügbar) on X server :0.
Speicherzugriffsfehler (Speicherabzug geschrieben)

This happens on two different machines with different operating systems, with two different HW1 dongles on different firmware versions and different USB transports.

**Comment by ulrichard** [comment]
When it doesn't crash right away, it displays the pin entry dialog and a message box saying the dongle was not connected simultaneously. After I click the message box away, it usually crashes.

**Comment by ulrichard** [comment]
The pixmap messages seem to be only warnings. The crash happens in:
plugins/btchipwallet.py   get_client()
plugins/btchipwallet.py   password_dialog()
gui/qt/password_dialog.py run_password_dialog()
  QDialog.exec_()

Messages that I get often are:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
and 
python2: ../../src/xcb_io.c:179: dequeue_pending_request: Zusicherung »!xcb_xlib_unknown_req_in_deq« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

**Comment by ulrichard** [comment]
One of the last successful transactions involved creating a second account. That day everything still seemed to work.
So the second account is the deciding factor!
If I revert the wallet file to a state when it contained only one account. The initialization progresses further. Rather than crashing immediately, it stalls somewhere on the way.
A simple workaround could be the following in the btchip plugin :

def can_create_accounts(self):
        return False

But I would prefer if I could use my hw1 again, which already has two accounts.

**Comment by ecdsa** [comment]
this is a segfault caused by non-gui threads calling gui calls.
it was fixed in the trezor plugin, but not in the hw1 plugin

**Comment by ulrichard** [comment]
I agree that the btchip plugin should be adapted. 
I tried it, but only came so far:  https://github.com/ulrichard/electrum/tree/btchip_ui_handler
But on the other hand, as long as I had funds on only one account, it still worked. Now with the second account used, I can go far back in the history, and it still doesn't work.
So I thought maybe I could introduce a mutex lock at the password dialog, but it didn't help.
The next idea would be to restrict the wallet to only load one account. Where would I have to make this temporary workaround?

**Comment by ulrichard** [comment]
That seems to do the trick for the time being : 
https://github.com/spesmilo/electrum/compare/master...ulrichard:btchip_one_account
