### ISSUE TITLE
Development instructions need updating

### ISSUE THREAD

**Issue by throwaway4536** [spesmilo/electrum#1723]
I have the Electrum 2.6.2 package working fine, but want to hack on Electrum. I checked out the repository and followed the instructions. However when I run electrum, I get this error:

Error: No module named dns. Try 'sudo pip install <module-name>'

And so:

$ sudo torsocks pip install dns
[sudo] password for dil: 
Downloading/unpacking dns
  Could not find any downloads that satisfy the requirement dns
Cleaning up...
No distributions at all found for dns
Storing debug log for failure in /home/dil/.pip/pip.log

Would appreciate knowing where to find this package. Thanks.

**Comment by ecdsa** [comment]
fixed in 5ae2f30fa52ebcec3773958fee45b462dd12c04e

**Comment by throwaway4536** [comment]
I don't want to install Electrum on my system. That can cause problems with if I want to use it, and also I'm uncomfortable installing stuff without packages.

So I instead ran: python setup.py build. Still the same error.

$ ./electrum 
Error: No module named dns. Try 'sudo pip install <module-name>'

**Comment by ecdsa** [comment]
well, in that case I guess you can either install as a user, or use a virtualenv, or open setup.py and see what the dependencies are inside, no?
