### ISSUE TITLE
2of3 multisig tx with 1 sig can't be loaded

### ISSUE THREAD

**Issue by ipojampon** [spesmilo/electrum#3059]
Trying to load a tx with Tools > Load transaction > from text 
Error:
```
Traceback (most recent call last):
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/gui/qt/main_window.py", line 2073, in do_process_from_text
    self.show_transaction(tx)
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/gui/qt/main_window.py", line 733, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/gui/qt/transaction_dialog.py", line 45, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/gui/qt/transaction_dialog.py", line 128, in __init__
    self.update()
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/gui/qt/transaction_dialog.py", line 184, in update
    self.sign_button.setEnabled(self.wallet.can_sign(self.tx))
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/lib/wallet.py", line 1099, in can_sign
    if k.can_sign(tx):
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/lib/keystore.py", line 76, in can_sign
    return bool(self.get_tx_derivations(tx))
  File "/home/amnesia/Persistent/Settingz/Electrum-2.9.3/lib/keystore.py", line 64, in get_tx_derivations
    if x_signatures[k] is not None:
IndexError: list index out of range
```
```
>> version()
"2.9.3"
```
Unsigned tx that CAN be loaded:
```
>> deserialize("0100000001bf22b7c83aa0931dd50e8b2a5ea20cc4ae3f80ee104c17f9f05d2ddf4f87f8760000000069522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153aeffffffff015c9d1c00000000001976a9147e333b15ef3f5ce73837b5e68e7d3b94d5f2b07188ac00000000")
{
    "inputs": [
        {
            "address": null, 
            "num_sig": 0, 
            "prevout_hash": "76f8874fdf2d5df0f9174c10ee803faec40ca25e2a8b0ed51d93a03ac8b722bf", 
            "prevout_n": 0, 
            "pubkeys": [], 
            "scriptSig": "522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153ae", 
            "sequence": 4294967295, 
            "signatures": {}, 
            "type": "unknown", 
            "x_pubkeys": []
        }
    ], 
    "lockTime": 0, 
    "outputs": [
        {
            "address": "1CWHWkTWaq1K5hevimJia3cyinQsrgXUvg", 
            "prevout_n": 0, 
            "scriptPubKey": "76a9147e333b15ef3f5ce73837b5e68e7d3b94d5f2b07188ac", 
            "type": 0, 
            "value": 1875292
        }
    ], 
    "version": 1
}
```

Same TX with one sig CAN'T be loaded:

```
>> deserialize("0100000001bf22b7c83aa0931dd50e8b2a5ea20cc4ae3f80ee104c17f9f05d2ddf4f87f87600000000b40047304402206472614c285244810880d9eac53799f1140ed20971072f12b3226947e02db7a9022079d4c8e3326308942f2d5344595d12c39fc5354ef50465682d623a9e937d2a18014c69522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153aeffffffff015c9d1c00000000001976a9147e333b15ef3f5ce73837b5e68e7d3b94d5f2b07188ac00000000")
{
    "inputs": [
        {
            "address": "3GaQMxGmWXmZuXtCQFjEi9F5iDwhXejohH", 
            "num_sig": 2, 
            "prevout_hash": "76f8874fdf2d5df0f9174c10ee803faec40ca25e2a8b0ed51d93a03ac8b722bf", 
            "prevout_n": 0, 
            "pubkeys": [
                "02d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c", 
                "0290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc23106191", 
                "02e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef4151"
            ], 
            "redeemScript": "522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153ae", 
            "scriptSig": "0047304402206472614c285244810880d9eac53799f1140ed20971072f12b3226947e02db7a9022079d4c8e3326308942f2d5344595d12c39fc5354ef50465682d623a9e937d2a18014c69522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153ae", 
            "sequence": 4294967295, 
            "signatures": [
                "304402206472614c285244810880d9eac53799f1140ed20971072f12b3226947e02db7a9022079d4c8e3326308942f2d5344595d12c39fc5354ef50465682d623a9e937d2a1801"
            ], 
            "type": "p2sh", 
            "x_pubkeys": [
                "02d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c", 
                "0290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc23106191", 
                "02e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef4151"
            ]
        }
    ], 
    "lockTime": 0, 
    "outputs": [
        {
            "address": "1CWHWkTWaq1K5hevimJia3cyinQsrgXUvg", 
            "prevout_n": 0, 
            "scriptPubKey": "76a9147e333b15ef3f5ce73837b5e68e7d3b94d5f2b07188ac", 
            "type": 0, 
            "value": 1875292
        }
    ], 
    "version": 1
}
```

**Comment by SomberNight** [comment]
How did create the tx? What tool did you use to sign? Electrum 2.9.3?

**Comment by ipojampon** [comment]
Used coinb.in this case but I've seen txs from other sources with the same problem (not sure how were those txs created but probably not with coinb.in)

**Comment by fivepiece** [comment]
Seems to be a few issues combined :

1. Partial signature signed by coinb.in did not add `0x00` to scriptsig for the second signature it couldn't* sign
2. Electrum is surprised by the lack of a second signature
3. Even with a correctly encoded partially signed transaction, electrum still fails pattern matching because it would skip the `0x00` where the invalid* signature would be

* a `0x00` is considered a valid encoded signature for the sole purpose of failing op_check(multi)sig, so placing one where a valid sig should be helps when signing in steps

A correct partial transaction encoding would be :
`0100000001bf22b7c83aa0931dd50e8b2a5ea20cc4ae3f80ee104c17f9f05d2ddf4f87f87600000000b600000047304402206472614c285244810880d9eac53799f1140ed20971072f12b3226947e02db7a9022079d4c8e3326308942f2d5344595d12c39fc5354ef50465682d623a9e937d2a18014c69522102d1ae61c48d4538e71020713c399ea8ba33961a6228407ac111e5007e63b8925c210290952dd39d75397287c4ab8aa966bf687f4d9bea97f44e98c38838fc231061912102e02142f91e1554df5e97e9f3d49dd315da31b949efff71f846d44b87f6ef415153aeffffffff015c9d1c00000000001976a9147e333b15ef3f5ce73837b5e68e7d3b94d5f2b07188ac00000000`
But electrum will not match it to p2sh(multisig) because of (3)

If applied :

```diff
diff --git a/lib/transaction.py b/lib/transaction.py
index 5317f715..8febc85e 100644
--- a/lib/transaction.py
+++ b/lib/transaction.py
@@ -276,7 +276,7 @@ def match_decoded(decoded, to_match):
     if len(decoded) != len(to_match):
         return False;
     for i in range(len(decoded)):
-        if to_match[i] == opcodes.OP_PUSHDATA4 and decoded[i][0] <= opcodes.OP_PUSHDATA4 and decoded[i][0]>0:
+        if to_match[i] == opcodes.OP_PUSHDATA4 and decoded[i][0] <= opcodes.OP_PUSHDATA4 and decoded[i][0]>=0:
             continue  # Opcodes below OP_PUSHDATA4 all just push data onto stack, and are equivalent.
         if to_match[i] != decoded[i][0]:
             return False
```

Then it's possible to both deserialize and load the transaction correctly in gui, but I can't tell if it'll sign successfully (replace the `0x00` before the last signature with a valid signature).

**Comment by ecdsa** [comment]
what is the point of adding that patch?
transaction signing will still fail, because they dont use the same format as electrum

**Comment by fivepiece** [comment]
@ecdsa even if it would've added it, electrum would still fail to pattern-match the script to a p2sh(multisig) (at least that I've tried).  With that patch it will also match the `0x00` to recognize a multisig.  This isn't a fix (also why I didn't submit anything, just posted the diff), but it's something I noticed.

**Comment by ecdsa** [comment]
I believe it should be possible to change Electrum's NO_SIGNATURE value in transaction.py, and use an empty string instead. this would require some testing.

**Comment by kyuupichan** [comment]
FWIW I just fixed "get_tx_derivations" in git HEAD in ElectrumSV.  This seems to have been broken in Electrum for years; likely since multisig was first introduced.  Anyone trying multisig m-of-n with 1 < m < n would hit it I believe.

**Comment by SomberNight** [comment]
Since the PSBT changes (https://github.com/spesmilo/electrum/pull/5721), this issue is now outdated.
Most of the related code was rewritten/changed.

Note that for partial transactions, we now only support PSBTs, so unless coinb.in supports them too, it will still not work. This will not be fixed however; others should adopt PSBT support too.
