### ISSUE TITLE
Version 4.0.4 Insuficient fund problem

### ISSUE THREAD

**Issue by cimetovsan** [spesmilo/electrum#6721]
I keep getting the insuficient fund error with my electrum wallet, even thout i have much more funds than necessary to send. whatever i do, there is no way i can send my funds to other place, not even a small portion of my funds...
can you please help me resolve this issue?

**Comment by ecdsa** [comment]
I believe this has the same cause as #6713 : we do not display the fee in the send tab

**Comment by cimetovsan** [comment]
i understand, but, there is no way i can use my funds, no matter what amount i pick to send, i get the same error message... and my funds are practically unusable... :// is there any way around this?

**Comment by ecdsa** [comment]
what happens if you click on "max"?

**Comment by cimetovsan** [comment]
when i click on "max" it says thee same "Insufficient funds"

basically my funds are frozen here... and I'm not able to use them... its a big problem, and i hope someone can help me solve this....

**Comment by sureplus1988** [comment]
What now

**Comment by ecdsa** [comment]
it should be fixed by 9fced6d2b1f22bc3023b7a927776dcfb9d128d30
Use version 4.0.5, you should be able to access the fee dialog.

**Comment by cimetovsan** [comment]
> it should be fixed by [9fced6d](https://github.com/spesmilo/electrum/commit/9fced6d2b1f22bc3023b7a927776dcfb9d128d30)
> Use version 4.0.5, you should be able to access the fee dialog.

so can you explain to me what should i do to be able to use my funds? 
sorry for being a nob...

**Comment by ecdsa** [comment]
@cimetovsan click 'max' and adjust the fee in the popup dialog
if you received a lot of small value transactions, the default fee might be higher than your balance

**Comment by cimetovsan** [comment]
> @cimetovsan click 'max' and adjust the fee in the popup dialog
> if you received a lot of small value transactions, the default fee might be higher than your balance

i do use 4.0.5 version, and still, when i press max, i still get the same "insuficient fund error "
it never brings me to the fee dialog...:/ 
even thou i do have sufficient funds in my wallet. 
there are also no pending transactions or anything... 

balance is written clearly, and whatever i do, or however much i try to send, with "max" or without, i always get the same popup " insuficient fund error "

it feels frustrating, because my funds are basically blocked here, and i dont know what to do with this...

**Comment by ecdsa** [comment]
what is the title of the popup you see?

**Comment by cimetovsan** [comment]
Insufficient funds


Sent from Yahoo Mail for iPhone


On Wednesday, December 2, 2020, 8:37 PM, ThomasV <notifications@github.com> wrote:




what is the title of the popup you see?

**Comment by ecdsa** [comment]
please post a screenshot

**Comment by cimetovsan** [comment]
On Thursday, December 3, 2020, 03:54:07 PM GMT+8, ThomasV <notifications@github.com> wrote:  
 
 


please post a screenshot

**Comment by SomberNight** [comment]
We cannot see a screenshot. I don't think picture attachements from emails work.

In statusbar>`Wallet`>`Information`, what is `Wallet type`?
