### ISSUE TITLE
Can't send sats

### ISSUE THREAD

**Issue by Virbac32** [spesmilo/electrum#9078]
Hi, I'm having issues trying to transfer out of Electrum. I have never used this forum. So If I'm posting this in the wrong section, could someone please advise where I get help?
I have used the wallet successfully for 6 months in conjunction with a ledger. I currently can't send funds either on chain, or with Lightning. I keep getting error notification. I haven't altered the node settings at all. I have 3 pics below with what's happening. I'm getting concerned about not being able to retrieve my Bitcoin. I am quite inexperienced as you can tell. Someone please help!
![electrum home page](https://github.com/spesmilo/electrum/assets/113769157/9847a7f3-922f-414b-aca8-ae23de4968fb)
The first screenshot is just history of my transactions. 
The second shot is the error I get when I try to send the maximum amount available on chain. It doesn't appear to pick up the ledger after I hit pay. No problems with the ledger while using Sparrow wallet though.
![Screenshot electrum on chain transaction](https://github.com/spesmilo/electrum/assets/113769157/c80b8fff-6f21-4148-99be-328967028e87)
The third screenshot is the error message I get when trying to do a lightning transaction. 
AS I said earlier, sorry if this section is for devs only. I'm flying blind, and need some assistance please.
![Screenshot lightning transaction](https://github.com/spesmilo/electrum/assets/113769157/f03b4d28-3590-43cb-b979-003c937bcff0)
Fourth screenshot is lightning channels open
![Lightning channels](https://github.com/spesmilo/electrum/assets/113769157/07fff5c8-57d0-437f-ab2f-19872af75371)

**Comment by SomberNight** [comment]
In your history, there are two local transactions, corresponding to lightning-channel-opens. It seems to me you did not intend this, so you should probably just try to right-click>remove those.

> It doesn't appear to pick up the ledger after I hit pay.

More details needed. What exactly happens, do you get an error message?
Could you try to test signing a message with the ledger? (go into "Addresses" tab, and right-click>"Sign/verify message")

>  The third screenshot is the error message I get when trying to do a lightning transaction.
> "Server did not reply in time."

You are trying to pay an LNURL, and it looks like that the server corresponding to the recipient is not responding. This is likely a problem on their side. Or if it's some large merchant you are sure should be working, maybe you are IP-banned by them. Try paying someone else.

**Comment by Virbac32** [comment]
Ok thanks for replying. I clicked remove the 2 lightning channels as you advised. And yes you're correct, I didn't mean to open them. I also checked the Ledger in a test sign. and it connected ok. But I still can't sign an on chain transaction. I am getting the attached window pop up. I hit sign, but it just goes back to the main page, and says the transaction is unpaid? I right click it again, and hit pay. Same thing happens. The transaction won't go through, remains unpaid..
![electrum 1](https://github.com/spesmilo/electrum/assets/113769157/5622d77c-13b2-4aa8-99ae-2b883574c7c8)
![electrum 2](https://github.com/spesmilo/electrum/assets/113769157/7e3947d1-c78a-449b-9304-f384b51b10a1)

**Comment by SomberNight** [comment]
> I still can't sign an on chain transaction. I am getting the attached window pop up. I hit sign, but it just goes back to the main page, and says the transaction is unpaid? I right click it again, and hit pay. Same thing happens.

Could you enable [debug logging](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) and test it again?
After that, upload the logs here. (Either upload the whole file, or open it in a text editor and try to find the relevant parts - in particular "traceback"s and errors)
